<a href="https://colab.research.google.com/github/AnMichalina/data-science-bootcamp/blob/main/1_wprowadzenie/1_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

1D array

In [2]:
x = np.array([1,3])
x

array([1, 3])

In [3]:
print (x)

[1 3]


In [4]:
type(x)

numpy.ndarray

In [5]:
x.ndim # wymiar tablicy

1

In [6]:
x.shape #2 elementy

(2,)

In [7]:
x.size #liczba el-ów w tablicy

2

In [8]:
x.dtype

dtype('int64')

In [9]:
x = np.array([1,2,3,4.2,5,6,7.3])
print (x)

[1.  2.  3.  4.2 5.  6.  7.3]


In [10]:
x.dtype

dtype('float64')

2D array

In [11]:
x= np.array([[1,2], [2,-3]])
x

array([[ 1,  2],
       [ 2, -3]])

In [12]:
x.ndim

2

In [13]:
x.shape #2 wiersze, 2 kolumny

(2, 2)

In [14]:
x = np.array([[1,2,3], [4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


3D array

In [15]:
x = np.array(
    [[[1,2,3],
     [4,5,6]],

     [[7,8,9],
      [9,8,7]],
     
     [[1,2,3],
      [4,5,6]]]
      )
print (x)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [9 8 7]]

 [[1 2 3]
  [4 5 6]]]


In [16]:
x.ndim #3 elementy po dwa wiersze i dwie kolumny

3

In [17]:
x.shape

(3, 2, 3)

Typy danych

In [18]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [19]:
A = np.array([1,2,3], dtype='float')
A.dtype

dtype('float64')

In [20]:
A = np.array([1,2,3], dtype='complex')
A.dtype

dtype('complex128')

In [21]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [22]:
A = np.array([1,2.7,3.5], dtype='int')
A.dtype

dtype('int64')

In [23]:
A

array([1, 2, 3])

In [24]:
A = np.array([1,2,3], dtype='bool')
A

array([ True,  True,  True])

In [25]:
A = np.array([24,120,230], dtype=np.int8)
A.dtype

dtype('int8')

In [26]:
A = np.array([24,120,230], dtype=np.uint8) #0-255 dla pixeli
A.dtype

dtype('uint8')

Tworzenie tablic

In [27]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
np.zeros(shape=(4,10), dtype='int') #maski do computer vision - np. czarne tło

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [29]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [32]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [34]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [35]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [36]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [37]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [38]:
np.linspace(start=0,stop=1,num=10) #10 równo rozłożonych elementów z przedziału

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [39]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [40]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [41]:
A.reshape(3,-1) #-1 python automatycznie wykryje sam sobie ten drugi wymiar czyli 5 kolumn w tym wypadku

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [42]:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Podstawowe operacje na tablicach

In [43]:
A =np.array([3,4,2,1])
B= np.array([3,2,5,6])

print (A)
print (B)

[3 4 2 1]
[3 2 5 6]


In [44]:
A+B

array([6, 6, 7, 7])

In [45]:
A-B

array([ 0,  2, -3, -5])

In [46]:
A*B

array([ 9,  8, 10,  6])

In [47]:
A/B

array([1.        , 2.        , 0.4       , 0.16666667])

In [48]:
np.add(A,B)

array([6, 6, 7, 7])

In [49]:
np.subtract(A,B)

array([ 0,  2, -3, -5])

In [50]:
np.multiply(A,B)

array([ 9,  8, 10,  6])

In [51]:
np.divide(A,B)

array([1.        , 2.        , 0.4       , 0.16666667])

In [52]:
A+5

array([8, 9, 7, 6])

In [53]:
2*A

array([6, 8, 4, 2])

In [54]:
A+3*B

array([12, 10, 17, 19])

In [55]:
X = np.array([[1,3], [2,3]])
Y = np.array([[4,-1], [-2,9]])

print (X, '\n')
print (Y)

[[1 3]
 [2 3]] 

[[ 4 -1]
 [-2  9]]


In [56]:
X*Y #mnożenie po elementach względem odpowiednich miejsc

array([[ 4, -3],
       [-4, 27]])

In [57]:
np.dot(X, Y) #mnożenie macierzowe

array([[-2, 26],
       [ 2, 25]])

In [58]:
X.dot(Y)

array([[-2, 26],
       [ 2, 25]])

In [59]:
Y.dot(X)

array([[ 2,  9],
       [16, 21]])

In [60]:
X @ Y

array([[-2, 26],
       [ 2, 25]])

Generowanie liczb pseudolosowych

In [63]:
np.random.seed(0) #ziarno losowania - ten sam wynik losowania

In [64]:
np.random.randn(10) #randomowy rozkład normalny, tablica 10 losowych el-ów

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [65]:
np.random.randn(10, 4)

array([[ 0.14404357,  1.45427351,  0.76103773,  0.12167502],
       [ 0.44386323,  0.33367433,  1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574, -2.55298982,  0.6536186 ],
       [ 0.8644362 , -0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,  1.20237985],
       [-0.38732682, -0.30230275, -1.04855297, -1.42001794],
       [-1.70627019,  1.9507754 , -0.50965218, -0.4380743 ],
       [-1.25279536,  0.77749036, -1.61389785, -0.21274028]])

In [66]:
np.random.rand() #wartość losowa <0,1)

0.15896958364551972

In [67]:
np.random.rand(10)

array([0.11037514, 0.65632959, 0.13818295, 0.19658236, 0.36872517,
       0.82099323, 0.09710128, 0.83794491, 0.09609841, 0.97645947])

In [68]:
np.random.rand(10, 2)

array([[0.4686512 , 0.97676109],
       [0.60484552, 0.73926358],
       [0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895]])

In [71]:
np.random.randint(10) # zwróci liczbę całkowitą mniejszą niż 10 - randomowy integer

0

In [72]:
np.random.randint(low=10, high=101) #losowa liczba dwucyfrowa

42

In [73]:
np.random.randint(low=10, high=101, size=3) 

array([64, 10, 48])

In [74]:
np.random.choice([2,3,4,7,9]) # zwróci losowy element z tego obiektu - listy

7

In [75]:
np.random.choice(['python', 'java', 'r', 'sql'])

'r'

In [76]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
np.random.shuffle(data) #mieszanie na tym obiekcie od razu

In [78]:
data

array([7, 9, 2, 1, 6, 5, 0, 4, 8, 3])

Funkcje w numpy

In [79]:
np.exp(1)

2.718281828459045

In [81]:
np.sqrt(9)

3.0

In [82]:
np.all([2,4,5,6])

True

In [84]:
np.all([2,4,0,6])

False

In [85]:
np.any([1,2,3,4])

True

In [86]:
np.any([1,2,-3,4])

True

In [88]:
np.any([0,0,0,0])

False

In [89]:
bool(0)

False

In [91]:
bool(-10)

True

In [94]:
A = np.random.rand(5)
A

array([0.97857093, 0.11620191, 0.7670237 , 0.41182014, 0.67543908])

In [95]:
np.argmax(A) #indeks maksa w A

0

In [96]:
A[np.argmax(A)]

0.978570928420717

In [97]:
np.argmin(A) 

1

In [99]:
np.argsort(A) # pokazuje indeksy posortowanych wartości od najmniejszej do największej

array([1, 3, 4, 2, 0])

In [100]:
np.max(A)

0.978570928420717

In [101]:
np.min(A)

0.1162019096123944

In [102]:
np.mean(A)

0.5898111523513837

In [103]:
np.median(A)

0.675439081200236

In [104]:
np.std(A)

0.29861584340017977

Indeksowanie

In [106]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [107]:
#A[idx], A[start:stop], A[:stop], A[start:]

In [108]:
A[2]

2

In [109]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [110]:
A[:2]

array([0, 1])

In [112]:
A[[0,2]] #wycięty tylko indeks 0 i indeks 2

array([0, 2])

In [113]:
A[-1] 

19

In [114]:
A[10:15]

array([10, 11, 12, 13, 14])

In [116]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [117]:
A[0] #wycięty cały wiersz o indeksie 0

array([0, 1, 2, 3, 4])

In [118]:
A[1]

array([5, 6, 7, 8, 9])

In [119]:
A[:,0] #wycina pierwszą kolumnę

array([ 0,  5, 10, 15])

In [120]:
A[:, -1]

array([ 4,  9, 14, 19])

In [121]:
A[:,-2]

array([ 3,  8, 13, 18])

In [122]:
A[1,1] #współrzędne konkretnego punktu

6

In [123]:
A[1,3]

8

In [125]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [130]:
A[1,2]
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [129]:
A[1,2] =14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Iteracje po tablicach

In [131]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [132]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [133]:
for row in A:
  print(row[0])

0
5
10
15


In [134]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [135]:
for item in A.flat: #wypłaszczenie tablicy, iteracja element po elemencie
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


Zmiana rozmiaru tablic

In [136]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [137]:
A.shape

(4, 5)

In [138]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [140]:
A.ravel() #wypłaszcza dane, odwrotna operacja do reshape

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [141]:
A.T #kolumna na wiersz

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski logiczne

In [143]:
A = np.arange(start=-10, stop=10, step=0.5)
A= A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [144]:
A>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [145]:
A[A>0] #maska tylko el-y dodatnie

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [147]:
np.bitwise_and(A>-5,A<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [148]:
A[np.bitwise_and(A>-5,A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [149]:
np.bitwise_or(A<-5, A>5) #albo mniejsze od -5 albo większe od 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [150]:
A[np.bitwise_or(A<-5, A>5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])