<a href="https://colab.research.google.com/github/AnMichalina/data-science-bootcamp/blob/main/1_wpowadzenie/2_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Norma wektora, długość wektora

In [2]:
import numpy as np

In [3]:
v1 = np.array([-1,4]) #wektor v1 o współrzędnych 0 4, policzymy normę wektora to z pitagorasa
v1

array([-1,  4])

W przypadku, gdy dany zbiór jest przestrzenią wektorową, możemy wprowadzić funkcję mierzącą "długość" wektora. Funkcję tę nazwiemy normą.

In [4]:
np.linalg.norm(v1)

4.123105625617661

In [5]:
# w przestrzeni Rn to suma kwadratów i z tego pierwiastek - v2 to R3, gdzie 3 to wymiar
v2 = np.array([-10,10,13])
v2

array([-10,  10,  13])

In [6]:
np.linalg.norm(v2)

19.209372712298546

Odległość dwóch punktów w przestrzeni Rn

In [7]:
#R2 - na płaszczyźnie, gdzie p i q to punkty na tej płaszczyźnie
p = np.array([3,0])
q = np.array([0,4])

In [8]:
np.linalg.norm(p-q) #obliczamy wektor a potem jego długość czyli normę

5.0

In [9]:
# w przestrzeni np. R3
p = np.array([3,0, 1])
q = np.array([0,4, 2])

np.linalg.norm(p-q)

5.0990195135927845

Mnożenie macierzy

In [10]:
# Z macierz 2x1
# X kolumna = Y wiersze
X = np.array([[5,3], [3,9]])
Y = np.array([[1], [-1]])

print (X, '\n')
print (Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [11]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [12]:
Z.shape

(2, 1)

In [13]:
X = np.array([[2,-1,3], 
              [3,1,0]])

Y = np.array([[2,1,-1], 
              [0,-1,2],
              [3,2,0]])

print (X, '\n')
print (Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [14]:
np.dot(X,Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

Wyznacznik macierzy

In [15]:
# dla macierzy kwadratowej: IAI lub detA
A= np.array([[2,4], [-1, 3]])
A

array([[ 2,  4],
       [-1,  3]])

In [17]:
round(np.linalg.det(A))

10

Ślad macierzy, czyli suma elementów na przekątnej

In [18]:
A= np.array([[2,4], [-1, 3]])
np.trace(A)

5

Macierz jednostkowa - tyle samo wierszy i kolumn a na składniki to 1


In [19]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Macierz odwrotna

In [21]:
#AB = BA = I
A

array([[ 2,  4],
       [-1,  3]])

In [23]:
B =np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [27]:
np.set_printoptions(precision=4, suppress=True)
np.dot(A,B)

array([[1., 0.],
       [0., 1.]])

In [28]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

Macierz transponowana

In [29]:
A

array([[ 2,  4],
       [-1,  3]])

In [30]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [31]:
A.T

array([[ 2, -1],
       [ 4,  3]])

Rozwiązywanie układów równań

In [32]:
A = np.array([[2,4], [1,-1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [37]:
B = np.array([[10],[-1]])
print(B)

[[10]
 [-1]]


In [38]:
A_inv = np.linalg.inv(A)

In [39]:
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])